# Generated by Django 5.0.1 on 2024-02-12 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependents', models.IntegerField(blank=True, default=0)),
                ('education', models.IntegerField(default=0)),
                ('employed', models.IntegerField(default=0)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('score', models.IntegerField(default=500)),
                ('residential_assets', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('commercial_assets', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('luxury_assets', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('bank_assets', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_phone', models.CharField(blank=True, max_length=30)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('account_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('finance_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.financedatauser')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_read', models.BooleanField(default=False)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
                ('response_from', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermessages')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
