# Generated by Django 5.0.1 on 2024-01-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='account_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
