# Generated by Django 5.0.1 on 2024-02-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usermessages_message_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='response_from',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermessages'),
        ),
    ]
