# Generated by Django 5.0.1 on 2024-02-02 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usermessages_response_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='response_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usermessages'),
        ),
    ]
