# Generated by Django 5.0.1 on 2024-02-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_financedatauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedatauser',
            name='education',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financedatauser',
            name='employed',
            field=models.IntegerField(default=0),
        ),
    ]
